<a href="https://colab.research.google.com/github/solomon-williams/LetsUpgrade-AI-ML/blob/master/Day10Assignment.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

##Create an element-wise comparison (greater, greater_equal, less and less_equal) of two given arrays.

In [1]:
import numpy as np
x = np.array([3, 5])
y = np.array([2, 5])
print("Original numbers:")
print(x)
print(y)
print("Comparison - greater")
print(np.greater(x, y))
print("Comparison - greater_equal")
print(np.greater_equal(x, y))
print("Comparison - less")
print(np.less(x, y))
print("Comparison - less_equal")
print(np.less_equal(x, y))

Original numbers:
[3 5]
[2 5]
Comparison - greater
[ True False]
Comparison - greater_equal
[ True  True]
Comparison - less
[False False]
Comparison - less_equal
[False  True]


##Write a NumPy program to create an array of 10 zeros,10 ones, 10 fives.

In [2]:
import numpy as np
array=np.zeros(10)
print("An array of 10 zeros:")
print(array)
array=np.ones(10)
print("An array of 10 ones:")
print(array)
array=np.ones(10)*5
print("An array of 10 fives:")
print(array)

An array of 10 zeros:
[0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
An array of 10 ones:
[1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]
An array of 10 fives:
[5. 5. 5. 5. 5. 5. 5. 5. 5. 5.]


##Write a NumPy program to compute sum of all elements, sum of each column and sum of each row of a given array.

In [3]:
import numpy as np
x = np.array([[0,1,5],[2,3,6],[8,5,7]])
print("Original array:")
print(x)
print("Sum of all elements:")
print(np.sum(x))
print("Sum of each column:")
print(np.sum(x, axis=0))
print("Sum of each row:")
print(np.sum(x, axis=1))

Original array:
[[0 1 5]
 [2 3 6]
 [8 5 7]]
Sum of all elements:
37
Sum of each column:
[10  9 18]
Sum of each row:
[ 6 11 20]


##Write a NumPy program to add, subtract, multiply, divide arguments element-wise.

In [6]:
import numpy as np
Row = int(input("Enter the number of rows:")) 
Column = int(input("Enter the number of columns:")) 
  
print("Enter the entries in a single line (separated by space): ") 
  

entries = list(map(int, input().split())) 
entries1 = list(map(int, input().split()))  

matrix = np.array(entries).reshape(Row, Column)
matrix2 = np.array(entries1).reshape(Row, Column)
print("First matrix = ",matrix) 
print("Second matrix = ",matrix2)
print("Addition = ", matrix + matrix2 )
print("Substraction = ", matrix - matrix2 )
print("Multiplication = ", matrix * matrix2 )
print("Division = ", matrix / matrix2 )

Enter the number of rows:2
Enter the number of columns:3
Enter the entries in a single line (separated by space): 
1 2 3 4 5 6
2 5 8 9 6 3
First matrix =  [[1 2 3]
 [4 5 6]]
Second matrix =  [[2 5 8]
 [9 6 3]]
Addition =  [[ 3  7 11]
 [13 11  9]]
Substraction =  [[-1 -3 -5]
 [-5 -1  3]]
Multiplication =  [[ 2 10 24]
 [36 30 18]]
Division =  [[0.5        0.4        0.375     ]
 [0.44444444 0.83333333 2.        ]]


##Write a NumPy program to compute the trigonometric sine, cosine and tangent array of angles given in degree.


In [7]:
import numpy as np
print("sine: array of angles given in degrees")
print(np.sin(np.array((0., 30., 45., 60., 90.)) * np.pi / 180.))
print("cosine: array of angles given in degrees")
print(np.cos(np.array((0., 30., 45., 60., 90.)) * np.pi / 180.))
print("tangent: array of angles given in degrees")
print(np.tan(np.array((0., 30., 45., 60., 90.)) * np.pi / 180.))

sine: array of angles given in degrees
[0.         0.5        0.70710678 0.8660254  1.        ]
cosine: array of angles given in degrees
[1.00000000e+00 8.66025404e-01 7.07106781e-01 5.00000000e-01
 6.12323400e-17]
tangent: array of angles given in degrees
[0.00000000e+00 5.77350269e-01 1.00000000e+00 1.73205081e+00
 1.63312394e+16]


##Write a Pandas program to create and display a DataFrame from a specified dictionary data which has the index labels


In [10]:
import numpy as np
import pandas as pd

exam_data  = {'Name': ['Anastasia', 'Dima', 'Katherine', 'James', 'Emily', 'Michael', 'Matthew', 'Laura', 'Kevin', 'Jonas'],
        'Score': [12.5, 9, 16.5, np.nan, 9, 20, 14.5, np.nan, 8, 19],'Qualification_Status':['yes', 'no', 'yes', 'no','no','yes','yes','no','no','yes']}
labels = ['1', '2', '3', '4', '5', '6', '7', '8', '9', '10']

TB = pd.DataFrame(exam_data , index=labels)
print(TB)

         Name  Score Qualification_Status
1   Anastasia   12.5                  yes
2        Dima    9.0                   no
3   Katherine   16.5                  yes
4       James    NaN                   no
5       Emily    9.0                   no
6     Michael   20.0                  yes
7     Matthew   14.5                  yes
8       Laura    NaN                   no
9       Kevin    8.0                   no
10      Jonas   19.0                  yes


##Write a Pandas program to select the 'name' and 'score' columns from the following DataFrame.

In [12]:
import pandas as pd
import numpy as np

exam_data  = {'Name': ['Anastasia', 'Dima', 'Katherine', 'James', 'Emily', 'Michael', 'Matthew', 'Laura', 'Kevin', 'Jonas'],
        'Score': [12.5, 9, 16.5, np.nan, 9, 20, 14.5, np.nan, 8, 19],'Qualification_Status':['yes', 'no', 'yes', 'no','no','yes','yes','no','no','yes']}
labels = ['1', '2', '3', '4', '5', '6', '7', '8', '9', '10']

TB = pd.DataFrame(exam_data , index=labels)
#print(TB)
print(TB[['Name', 'Score']])

         Name  Score
1   Anastasia   12.5
2        Dima    9.0
3   Katherine   16.5
4       James    NaN
5       Emily    9.0
6     Michael   20.0
7     Matthew   14.5
8       Laura    NaN
9       Kevin    8.0
10      Jonas   19.0


##Write a Pandas program to join the two given dataframes along rows and assign all data.


In [13]:
import pandas as pd
import numpy as np

left = pd.DataFrame({'Key': ['K0', 'K1', 'K2', 'K3'], 
'A': ['A0', 'A1', 'A2', 'A3'], 
'B': ['B0', 'B1', 'B2', 'B3']}) 

right = pd.DataFrame({'Key': ['K0', 'K1', 'K2', 'K3'], 
'C': ['C0', 'C1', 'C2', 'C3'], 
'D': ['D0', 'D1', 'D2', 'D3']}) 


pd.merge(left, right, how ='inner', on ='Key')

Key   A   B   C   D
0  K0  A0  B0  C0  D0
1  K1  A1  B1  C1  D1
2  K2  A2  B2  C2  D2
3  K3  A3  B3  C3  D3

##Write a Pandas program to detect missing values of a given DataFrame. Display True or False.

In [14]:
import pandas as pd
import numpy as np

exam_data  = {'Name': ['Anastasia', 'Dima', np.nan, 'James', 'Emily', 'Michael', 'Matthew', np.nan, 'Kevin', 'Jonas'],
        'Score': [12.5, 9, 16.5, np.nan, 9, 20, 14.5, np.nan, 8, 19],'Qualification_Status':['yes', np.nan, 'yes', 'no','no','yes','yes','no','no','yes']}
labels = ['1', '2', '3', '4', '5', '6', '7', '8', '9', '10']

TB = pd.DataFrame(exam_data , index=labels)
#print(TB)
#print(TB[['name', 'score']])
TB.isnull()


Name  Score  Qualification_Status
1   False  False                 False
2   False  False                  True
3    True  False                 False
4   False   True                 False
5   False  False                 False
6   False  False                 False
7   False  False                 False
8    True   True                 False
9   False  False                 False
10  False  False                 False

##Write a Pandas program to create and display a one-dimensional array-like object containing an array of data.



In [15]:
import pandas as pd
import numpy as np

exam_data  = {'Even Numbers:': ['2', '4', '6', '8', '10', '12', '14', '16']}

TB = pd.DataFrame(exam_data)
print(TB)

  Even Numbers:
0             2
1             4
2             6
3             8
4            10
5            12
6            14
7            16
